### ISSUE TITLE
PIP installation instruction needs clarification

### ISSUE THREAD

**Issue by RayZ0rr** [ueber-devel/ueberzug#11]
At the moment there is no package named `ueberzug` in pip [when you search for it](https://pypi.org/search/?q=ueberzug)

But it is the [first installation step](https://github.com/ueber-devel/ueberzug#installation) suggested in the README.

So, maybe there needs to be more clarification on the status or correction on the instructions.

**Comment by gokberkgunes** [comment]
In the future if this issue still persists, please refer [here](https://github.com/gokberkgunes/ueberzug-tabbed/blob/master/readme.md).

**Comment by eylles** [comment]
Ah, yes work has been draining my time lately, would like to upload the package to pypi but cannot promise when.

**Comment by RayZ0rr** [comment]
Thanks for your contribution to the community. Since it exists in officials repos and can be installed from source like @gokberkgunes  mentions in his comment, I think it's not a big priority. Closing this as sufficient details have been provided.
