### ISSUE TITLE
ueberzug breaks after pillow 10.0 update

### ISSUE THREAD

**Issue by thomasjlsn** [ueber-devel/ueberzug#15]
I noticed image previews stop working this morning after an update. [This](https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#backwards-incompatible-changes) seems to be the cause.

I fixed the issue by replacing `Image.ANTIALIAS` with `Image.LANCZOS` in the following modules:

- `ueberzug.ui`
- `ueberzug.loading`
- `ueberzug.scaling`

I've tested this with versions of pillow back to 9.0 with no problems. I have not tested older versions yet.

Sorry I don't have time to write a PR right now, I hope this helps!

**Comment by lucas-mior** [comment]
Yes, downgrading pillow to 9.5 is a temporary solver for me.

**Comment by Jorpy76** [comment]
I fixed the issue by replacing Image.ANTIALIAS with Image.LANCZOS in the following modules:

ueberzug.ui
ueberzug.loading
ueberzug.scaling

Thank's you very much.. that work for me... :=)  ..  
Archlinux 
Pillow version 10.0.0

**Comment by eylles** [comment]
commit to master and a release tag is out.

**Comment by eylles** [comment]
forgot to close this
