### ISSUE TITLE
Minor: a place (or two) within the README where the English could be better

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [ueber-devel/ueberzug#8]
> Advantages to w3mimgdisplay:

That should be, `Advantages over w3mimgdisplay:`. Better yet: `Advantages over the program 'w3mimgdisplay':`.

> Überzug is a command line util which allows to draw images on terminals by using child windows.

I wondered why [you mentioned threats](https://www.reddit.com/r/linux/comments/12lc11t/ueberzug_1820_now_maintained_releases_on_april_15/), and now I see: you use child labour! To be a _little_ more serious: you might want to put the word 'child' within inverted commas. Also: 'allows to' is not the best English. 'Allows one to' - or 'lets one' - is better.

**Comment by eylles** [comment]
don't worry, we will fix all issues left by the original author, problem is teaching the kids how to python.

aaaand it seems the OG author didn't know how to english too well, will push the rewording to master soon.
